on:
  push:
    branches:
      - master









jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login Dockerhub"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}

      - name: "building docker image"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/mahmoud . 

      - name: "push to Docker hub"
        run: docker push ${{secrets.DOCKER_USERNAME}}/mahmoud 
